### ISSUE TITLE
Criar modelagem de dados do MVP

### ISSUE THREAD

**Issue by alexsandro225** [lucassiqueira08/app_confia#2]
Neste tópico iremos entender e desenhar o banco de dados da aplicação.

**Comment by alexsandro225** [comment]
![Banco MVP Confia](https://user-images.githubusercontent.com/15957977/71689930-03255c80-2d82-11ea-8a26-7c578e6851ba.jpeg)

**Comment by lucassiqueira08** [comment]
![Banco MVP Confia](https://user-images.githubusercontent.com/30813702/71740528-3972e280-2e3b-11ea-9e48-8010d4e905c9.png)
